export const state = {
  usuarios: [],
  produtos: [],
  movimentacoes: [],
  pacientes: [],
  pacienteDetalheId: null,
  formPacienteId: null,
  formProcedimentosDesejados: [],
  currentUser: null,
  activeTab: 'dashboard',
  loginError: '',
  confirmModal: null,
  mostrarFormNovoProduto: false,
  produtoMovimentandoId: null,
  buscaCatalogo: '',
  sidebarColapsada: false,
  mostrarPerfil: false,
  resetTokens: [],
  resetTokenAtivo: null,
  telaEsqueciSenha: false,
  resetLinkGerado: null
};